[package]
name = "sointty-output-wasapi"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[target.'cfg(windows)'.dependencies]
sointty-core.workspace = true
rtrb.workspace = true
audio_thread_priority.workspace = true
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Media_Audio",
    "Win32_Security",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Threading",
    "Win32_System_Variant",
    "Win32_UI_Shell_PropertiesSystem",
] }

[dependencies]
sointty-core.workspace = true
